---
# see https://github.com/Valve/ansible-jetty-solr/blob/master/solr/production/ansible/provision.yml
- name: install packages for Oracle JDK 7
  tags: java
  apt: pkg={{item}} state=latest
  with_items:
    - debconf
    - debconf-utils

- name: add webupd8team repo
  apt_repository: repo="ppa:webupd8team/java"
  tags: java

- name: retrieve status of oracle licences
  tags: java
  shell: >
    debconf-get-selections | grep -q {{item}} && echo -n 'yes' || echo -n 'no'
  register: java_license_status
  changed_when: False
  with_items: java_ora_versions

- name: accept oracle licenses
  tags: java
  shell: >
    /bin/echo -e {{item.item}} shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  when: item.stdout != "yes"
  with_items: java_license_status.results

- name: install Oracle JDK 8
  tags: java
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    -  oracle-java8-installer
    -  oracle-java8-set-default