---
# application tasks to be customized and to run after the main provision
- name: Create tmpfs
  sudo: yes
  mount: name=/mnt/tmpfs src=none fstype=tmpfs opts="size=256m" state=mounted

- name: Setup watcher nfs cache clearing
  sudo: yes
  shell: watch -n16 "sysctl -w vm.drop_caches=3" > /dev/null &
  when: inventory_hostname == "192.168.56.128"